version: '3'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile.wordpress
    ports:
      - '80:80'
    volumes:
      - "wp:/var/www/html:rw"
      - "./plugin-boilerplate:/var/www/html/wp-content/plugins/plugin-boilerplate:rw"
      - "./.htaccess.wordpress:/var/www/html/.htaccess"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: "true"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: start_with_request=yes client_host=172.17.0.1 client_port=9000
volumes:
  db_data:
  wp: